## Switches
set_property PACKAGE_PIN V17 [get_ports {e1}]
    set_property IOSTANDARD LVCMOS33 [get_ports {e1}]
set_property PACKAGE_PIN V16 [get_ports {e2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e2}]

set_property PACKAGE_PIN T2 [get_ports {e11}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e11}]
set_property PACKAGE_PIN R3 [get_ports {e12}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e12}]
set_property PACKAGE_PIN W2 [get_ports {e13}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e13}]
set_property PACKAGE_PIN U1 [get_ports {e14}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e14}]
set_property PACKAGE_PIN T1 [get_ports {e15}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e15}]
set_property PACKAGE_PIN R2 [get_ports {e16}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e16}]
 

## LEDs
set_property PACKAGE_PIN U16 [get_ports {l1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l1}]
set_property PACKAGE_PIN E19 [get_ports {l2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l2}]

set_property PACKAGE_PIN W3 [get_ports {l11}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l11}]
set_property PACKAGE_PIN U3 [get_ports {l12}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l12}]
set_property PACKAGE_PIN P3 [get_ports {l13}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l13}]
set_property PACKAGE_PIN N3 [get_ports {l14}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l14}]
set_property PACKAGE_PIN P1 [get_ports {l15}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l15}]
set_property PACKAGE_PIN L1 [get_ports {l16}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l16}]
	
	
## Display block
set_property PACKAGE_PIN W7 [get_ports {a}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a}]
set_property PACKAGE_PIN W6 [get_ports {b}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b}]
set_property PACKAGE_PIN U8 [get_ports {c}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {c}]
set_property PACKAGE_PIN V8 [get_ports {d}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d}]
set_property PACKAGE_PIN U5 [get_ports {e}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e}]
set_property PACKAGE_PIN V5 [get_ports {f}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {f}]
set_property PACKAGE_PIN U7 [get_ports {g}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {g}]

set_property PACKAGE_PIN V7 [get_ports dp]							
	set_property IOSTANDARD LVCMOS33 [get_ports dp]