set_property PACKAGE_PIN V17 [get_ports {e1}]
    set_property IOSTANDARD LVCMOS33 [get_ports {e1}]
set_property PACKAGE_PIN V16 [get_ports {e2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e2}]
	
set_property PACKAGE_PIN U16 [get_ports {l1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l1}]
set_property PACKAGE_PIN E19 [get_ports {l2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {l2}]

set_property PACKAGE_PIN W7 [get_ports {a}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a}]
set_property PACKAGE_PIN W6 [get_ports {b}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b}]
set_property PACKAGE_PIN U8 [get_ports {c}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {c}]
set_property PACKAGE_PIN V8 [get_ports {d}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {d}]
set_property PACKAGE_PIN U5 [get_ports {e}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {e}]
set_property PACKAGE_PIN V5 [get_ports {f}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {f}]
set_property PACKAGE_PIN U7 [get_ports {g}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {g}]

set_property PACKAGE_PIN V7 [get_ports dp]							
	set_property IOSTANDARD LVCMOS33 [get_ports dp]